#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Onion Corporation
#
START=99

USE_PROCD=1

BIN="/usr/bin/power-dock2"

start_service() {
        procd_open_instance
        procd_set_param command "$BIN"
        procd_append_param command -j -l 60
        procd_set_param respawn
        procd_set_param stdout 1 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        procd_close_instance
}
